### ISSUE TITLE
No OSS licensing?

### ISSUE THREAD

**Issue by InDieTasten** [FitzyCodesThings/core-lms#1]
Hi, I just had the same idea to build an LMS as an extension to ASP.NET Core. I found your repo while looking for projects, that might already do this.

I would be interested to learn a bit more about the project, if it were to go OSS with some license, preferably MIT.

**Comment by InDieTasten** [comment]
Bump

**Comment by FitzyCodesThings** [comment]
Great point on the OSS licensing! I'll get that tended ASAP (and MIT is fine as far as I'm concerned). 

In terms of it being an "extension" to ASP.Net Core, not entirely sure what you mean (I don't intend for this to be a Nuget package or anything), but by all means, if it helps you on your journey (or if you have anything to contribute back along the way), jump in!

**Comment by enuraindula** [comment]
Is there any database file available for the Core LMS? I can't find it in the file! Please help!

**Comment by FitzyCodesThings** [comment]
MIT license added to primary README, will investigate adding elsewhere as well.
