### ISSUE TITLE
Is there documentation available?

### ISSUE THREAD

**Issue by InDieTasten** [FitzyCodesThings/core-lms#2]
How does this project fit inside the ASP.NET Core ecosystem?

Is it a standalone app or will it be a available in a nuget package?

What is the roadmap. What are current features and planned features?

The wiki is currently empty. I'd like to know more about the plans for this project.

**Comment by InDieTasten** [comment]
Bump

**Comment by FitzyCodesThings** [comment]
I touched on this in the other issue, but this will be a standalone app with the core functionality of a learning management system.

I detailed my thinking and early planning for the project here: 
https://dev.to/fitzycodesthings/corelms-let-s-build-a-cleanish-solidish-lms-from-scratch-in-asp-net-core-34hh

(I also try to keep that series up with progress which will be resuming next week.)

This is an "as I have time to do it" project, and I'm building it to be both a solid starting point for an LMS including e-commerce functionality AND a logical starting point for updating a system I've built for the last nearly 15 years as a custom app for a client (the parts I build in CoreLMS ARE open source).
