### ISSUE TITLE
Active or discontinued?

### ISSUE THREAD

**Issue by InDieTasten** [FitzyCodesThings/core-lms#3]
Is this still an active project?

**Comment by FitzyCodesThings** [comment]
Hello! My apologies, end of 2020 was a HASSLE (sold my company/started a new role, super busy season, etc.). 

I AM continuing work on this project (I broadcast my work on it live on Twitch at https://twitch.tv/fitzycodesthings).

I'll also follow up to your other issues now. Thanks!

**Comment by InDieTasten** [comment]
No worries. I know how tough it can be. Best of luck with your new chapter of life :)
