### ISSUE TITLE
Database File

### ISSUE THREAD

**Issue by enuraindula** [FitzyCodesThings/core-lms#4]
Is there any database file available for the Core LMS? I can't find it in the file! Please help!

**Comment by InDieTasten** [comment]
I've not looked into into the repo itself that much, but I wouldn't expect a database file to be part of the source repository.
It's probably using some ORM with migrations that can generate a database during runtime.

Information provided without guarantees though.

**Comment by FitzyCodesThings** [comment]
@InDieTasten has it right. This system uses the Entity Framework Core ORM, code-first, so what you'll see is that there are migration files that describe how to create the database from scratch.

A couple of notes:

1) This system is VERY early in development as it's a "learning in public" project for me. It's certainly not usable as-is as a learning management system

2) I'll try to record a segment in my stream today demonstrating how to get the database created and updated if you decide you want to start working on this code as-is or in the future.

**Comment by FitzyCodesThings** [comment]
I made a quick video (ish...) this evening walking through how the database is handled in CoreLMS. Hope it helps!

https://youtu.be/CRMxrZj8WFs

**Comment by MrRedBeard** [comment]
Works like a champ. I'm using SQL Express so I had to further change my connection string but same same
